### ISSUE TITLE
Create All Express routes, server running in Node.js

### ISSUE THREAD

**Issue by Yogibuff** [Yogibuff/SnowTracks#16]
This issue will cover the Node.js and Express initial setup and deployment of the back-end server.

TO DO:
[ ] Static Routes for Images, Javascript, and CSS
[ ] Server root (index.html)
[ ] About page and package.json routes set
[ ] SnoCountry API is connected via calling api.js
*\* set up, just commented out while editing api.js

**Comment by Yogibuff** [comment]
Seeing the following Error Message in Terminal, no errors in Console.

Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/Users/LeeDecker/SnowTracks/SnowTracks/node_modules/send/index.js:326:13)
    at SendStream.send (/Users/LeeDecker/SnowTracks/SnowTracks/node_modules/send/index.js:525:17)
    at onstat (/Users/LeeDecker/SnowTracks/SnowTracks/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by Yogibuff** [comment]
What I know so far about this Error:
- Directory (node_modules) holds the specific file mentioned "send/index.js". 
- After closely inspecting send/index.js, I found no corruptions. The code causing the error is lines 254-262, which clears headers and creates a basic response. (Set res.headers to null, Set to text/plain and charset UTF-8, Set content-option to 'no-sniff' - which rejects responses with incorrect MIME types)
- SnowTracks' file causing the error: js/ app.js

Solution : Running node debugger in app.js adjusting the breakpoint to test each route.

**Comment by Yogibuff** [comment]
This error occurs when opening index.html OR about-us.html

The issue is with the header section of the server's response messages, whose headers need to be cleared and set in server response messages. They were set by the .html document and failed to be cleared by the function within SendStream.prototype.error (lines 242-262) whose job it is to detect this error, clear all headers, and set the basic headers. 

The variable SendStream.prototype.send (line 514) was responsible for sending the above error message. I commented out the error message functionality and added a redundancy to remove the .html headers and set the proper basic headers. This (temporarily) solves the issue by ensuring the server response is in basic format, rather than following the headers of the html document that it is serving.

I was able to fix the bug with a code modification of the node_modules/send/index.js file
Starting with line 514 :

SendStream.prototype.send = function(path, stat){
// list of variables  
if (res._header) {
    // Part Added by ME: wipes all existing headers
    res._headers = null
    res.statusCode = status
    res.setHeader('Content-Type', 'text/plain; charset=UTF-8')
    res.setHeader('Content-Length', Buffer.byteLength(msg))
    res.setHeader('X-Content-Type-Options', 'nosniff')
    res.end(msg)
  }

Instead of sending a very long and unhelpful error message, it now actually fixes the root of the problem.
*\* These changes are only viewable in js/modified-index.js
*\* I did not modify the node_modules/send/index.js
*\* I am looking for a permanent solution, since editing the node module would require a download of the modified module files rather than simply downloading the dependencies listed in my package/json file.

**Comment by Yogibuff** [comment]
Updated TO DO's:

[X] Static Routes for Images, Javascript, and CSS
[X] Server root (index.html)
[X] About page and package.json routes set
[  ] Long-term solution for headers bug

**Comment by Yogibuff** [comment]
[X] Bug Status : Terminated.  :+1: 

Explanation:

After re-reading the Express.js documentation and the use of "next", I realized that my route for " / ", " /index.html ", and " /about.html " actually did NEED to call next() since those files have custom headers and apparently their headers were not effectively set (while the routers for /css, /images, /js, and package.json did not cause any errors).

The lack of next() in these routes that handled .html files caused the server response function (Express middleware file /node_modules/send/index.js) to have an issue clearing these header styles from the html document and setting basic headers for the server's response in the terminal.

<i>TLDR:</i>
- app.js lines 10-24 now functional, correcting this bug and closing this issue.
